### ISSUE TITLE
AUX mainnet tracking issue

### ISSUE THREAD

**Issue by leina05** [aux-exchange/aux-exchange#3]
# Contract

- [x] getting rid of vectors, inlining constants, etc.
- [x] open orders + better cancelAll
- [x] lot/tick size modification. on change, cancel orders that don't evenly divide new sizes
- [x] vault refactoring to use coin
- [x] refactor AMM to use coin
- [x] storage gas optimization
- [x] handle fee changes in available balance (ie can't be refunded more/less than was placed on hold)
- [x] privatize all possible functions
- [x] DoS attack vectors with level sizes
- [x] ~~deploy AMM to separate resource account from vault/clob~~
- [x] Remove cancel queue
- [x] Consolidate `clob` / `clob_market` to cut down on vectors
- [x] ~~Type events on market/pool tokens~~
- [x] delete flash_swap_example.move
- [x] can our forked simple_map be combined with volume tracker?
- [x] could we inline function calls in fee? seem to be one liners just borrowing used only internally in the module
- [x] Update `add_liquidity` to accept max and min amounts and automatically deposit correct ratio (think this just means it should use `add_approximate_liquidity`
- [x] aux AU burned should be per lot instead of per AU quantity
- [ ] cancel timeout should attach some APT based on our benchmarked gas cost to compensate the sender who removes it
- [x] rounding error on balance holds due to fee hold...perhaps remove the fee hold and just place hold on the order quantity
- [x] convert all integer struct fields stored in global storage to smallest size possible and cast where necessary
- [x] remove `create_vault()` if unnecessary
- [x] router API accepts `Coin`
- [x] refactor router to remove `simplify()`
- [x] rename trailing `_` functions to meaningful names (such as `_with_signer`).
- [x] Move net fees to vault owned by `@aux`

# SDK

- [x] Router/AMM quoting
- [ ] Cancel all function that reads from open orders
- [ ] Helper functions to determine exact token ratios for adding liquidity
- [ ] 24hr pool volumes
- [x] L1 orderbook parsing
- [ ] Better support for simulating txs to quote prices and get gas estimates (should not require `signer`, only account address)

# UI

- [ ] more granular pool coins endpoint: all available coins, what coins exist in pools already, what Y coin exists for a given X coin in the dropdown

**Comment by Manahip** [comment]
For integration with hippo-aggregator, it would be helpful to have a signer-less, coin-in, coin-out interface like:
```
public fun coin_swap_exact_coin_for_coin<CoinIn, CoinOut>(
  coin_in: &mut coin::Coin<CoinIn>,
) : coin::Coin<CoinOut> { ... }
```

For an aggregator, we really don't want to pass our user's &signer to an underlying DEX contract to avoid any potential exploit at all. By passing in a coin object only the security assumptions are dramatically simplified.

**Comment by Manahip** [comment]
Currently the AMM has a coin-in, coin-out interface that more or less works for our needs. We'll just pass in a resource account signer instead of user's signer object.

Would be super nice to have a similar coin-in, coin-out interface for clob IOC orders!

**Comment by leina05** [comment]
> Currently the AMM has a coin-in, coin-out interface that more or less works for our needs. We'll just pass in a resource account signer instead of user's signer object.
> 
> Would be super nice to have a similar coin-in, coin-out interface for clob IOC orders!

Thanks for the feedback @Manahip! We were planning to update the `router` module to accept `CoinIn` and `CoinOut`--this has the same API as the AMM and will execute on the CLOB, AMM or both depending on execution price. We recommend most orders to go through the router. Would that meet your needs?

**Comment by Manahip** [comment]
Yes going through the router is okay. Though if you expose it in
clob_market too that’ll give the aggregator maximal flexibility in planning
(for example for split-transactions in the future)
