### ISSUE TITLE
UI Cleanups Tracking Issue

### ISSUE THREAD

**Issue by yuhanfang** [aux-exchange/aux-exchange#82]
- [x] Time since pool action seems off https://mainnet.aux.exchange/pool?coinx=0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb%3A%3Acoin%3A%3AT&coiny=0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea%3A%3Acoin%3A%3AT
- [x] Pagination of TradingView
- [x] Swap should not be allowed if insufficient liquidity in pool
- [x] Distinguish USDC-eth vs USDC-sol
- [x] Display swap events in pools
- [x] Validator of decimals/lot/ticks in the price and amount fields of CLOB
- [x] More intuitive onboarding for AUX account creation and funding. Maybe prompt on loading the UI if no account exists for that user?
- [x] Allow adding decimals in a new pool
- [x] Account struct creation for first-time users
- [x] Detect whether wallet is installed and give hint if not
- [x] Grey out create AUX account when it's already created
- [x] More responsive UI refresh after deposit or withdraw
- [x] Scroll down order book asks side
- [x] Swap fractional 
- [x] Swap should register coin if not registered
- [x] Add graphql endpoint for whether user has an AUX account, use to grey out create AUX account
- [x] Script trading view configuration
- [x] Swap UI should display anticipated quantity with slippage

Nice to have:
- [x] UI Blocked - TX hashes not coming back from GraphQL - Add tx hashes and times to swap events in pool view
- [x] Click the orderbook level to fill in the price in the order dialog
- [x] Order type tool tips

**Comment by lelandriordan** [comment]
- [x] Fix Logo
- [ ] Profile page workflow
- [ ] time.time console error market trades
- [ ] Orderbook data not updating when switching markets
- [ ] TV Error on refresh from team chat (tvColorPallete localStorage variable)
- [ ] Add search to pools page

**Comment by yuhanfang** [comment]
For Mojito:

- [ ] Highlight market (MOJO/APT in this case) in the pools list
- [ ] Swap button when clicking into a pool in the pools view next to add/remove
- [ ] Remove the "Earn AUX" part of the pools page description
- [ ] change the green background? Either the background in the Figma or a even plain colour (similar to header colour)
- [ ] Add text besides logo similar to their main website
- [ ] Per-project customization of top navigation. For Mojito, disable or "Coming Soon" the Trade/Portfolio view

**Comment by yuhanfang** [comment]
New pool page:

- [ ] Back button from specific pool
- [ ] Wording of pool bps on create
